# Generated by Django 3.1.1 on 2020-12-20 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(max_length=300)),
                ('domain', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('price_th', models.CharField(max_length=10)),
                ('product_pic_url', models.URLField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
