# Generated by Django 3.1.1 on 2020-12-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkadd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
