# Generated by Django 3.1.1 on 2020-12-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkadd', '0002_auto_20201220_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product_pic_url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='product_url',
            field=models.URLField(max_length=400),
        ),
    ]
