# Generated by Django 3.1.1 on 2020-12-26 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linkadd', '0003_auto_20201220_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='availability',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
