# Generated by Django 3.1.1 on 2020-12-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkadd', '0006_watchlist_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='pid',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
