# Generated by Django 3.1.1 on 2021-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkadd', '0007_watchlist_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
