# Generated by Django 3.1.1 on 2021-01-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkadd', '0008_mailinglist_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product_name',
            field=models.CharField(max_length=150),
        ),
    ]
