# Generated by Django 3.1.14 on 2025-02-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkadd', '0009_auto_20210121_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product_pic_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='product_url',
            field=models.TextField(),
        ),
    ]
