# Generated by Django 4.2.19 on 2025-02-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkadd", "0011_auto_20250215_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
